services:
  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8090:80"
    networks:
      - webnet
  web1:
    image: nginx:latest
    #ports:
    #  - "8081:80"
    volumes:
      - ./web1:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - webnet
  web2:
    image: nginx:latest
    #ports:
    #  - "8082:80"
    volumes:
      - ./web2:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - webnet

networks:
  webnet:
    # Specify driver options
    driver: bridge
    